CREATE DATABASE JOINS;
USE JOINS;
CREATE TABLE STUDENT(
	ID INT,
    SNAME VARCHAR(100)
);

INSERT INTO STUDENT VALUES(1,"VARUN"),(2,"MANOJ"),(3,"SHEERISH"),(4,"GANESH");

CREATE TABLE COURSE(
	CID INT,
    CNAME VARCHAR(100)
);

INSERT INTO COURSE VALUES(1,"ECE"),(2,"EEE"),(1,"CSE"),(3,"IT");

SELECT * FROM STUDENT;
SELECT * FROM COURSE;
-- INNER  JOIN
SELECT ID,SNAME FROM STUDENT
INNER JOIN COURSE
ON STUDENT.ID=COURSE.CID;

SELECT CID,CNAME FROM COURSE
INNER JOIN STUDENT
ON COURSE.CID=STUDENT.ID;


-- LEFT JOIN
SELECT ID,SNAME FROM STUDENT
LEFT JOIN COURSE
ON STUDENT.ID=COURSE.CID;

-- RIGHT JOIN
SELECT ID,SNAME FROM STUDENT
RIGHT JOIN COURSE
ON STUDENT.ID=COURSE.CID;

-- FULL OUTER JOIN
SELECT S.ID, S.SNAME, C.CID, C.CNAME
FROM STUDENT S
LEFT JOIN COURSE C ON S.ID = C.CID
UNION
SELECT S.ID, S.SNAME, C.CID, C.CNAME
FROM STUDENT S
RIGHT JOIN COURSE C ON S.ID = C.CID
ORDER BY ID, CID;

-- SELF JOIN 
CREATE TABLE EMPLOYEE(
EID INT,
FNAME VARCHAR(100),
LNAME VARCHAR(100),
MGID int
);

INSERT INTO EMPLOYEE(EID,FNAME,LNAME) VALUES(1,"JOHN","DOE");
INSERT INTO EMPLOYEE VALUES(2,"JANE","SMITH",1),
(3,"ALICE","JOHNSON",1),(4,"BOB","BROWN",2),(5,"EMILY","DAVIS",2),
(6,"MICHAEL","WILSON",3),(7,"SARAH","TAYOLR",4),(8,"DAVID","ANDERSON",4);

SELECT * FROM EMPLOYEE;
/*Using a self join, write a query to display each employee's first name along
 with their manager's first name. If an employee does not have a manager (i.e., ManagerID is NULL),
 the manager's name should be displayed as 'No Manager'.*/
 
SELECT 
    e1.FNAME AS EmployeeFName,
    COALESCE(e2.FName, 'No Manager') AS MFName
FROM 
    Employee e1
LEFT JOIN 
    EmployeE e2 ON e1.MGID = e2.EID;

CREATE TABLE COLORS(
COLOR1 VARCHAR(100),
SNAME VARCHAR(100),
COLOR2 VARCHAR(100)
);

INSERT INTO COLORS VALUES("RED","VARUN","BLUE"),("YELLOW","DINESH","GREEN"),("BLUE","MOULI","RED"),("GREEN","KISHORE","YELLOW");
SELECT * FROM COLORS;


SELECT A.SNAME AS NAME,B.SNAME AS SECRETSANTA 
FROM COLORS AS A,COLORS AS B WHERE
A.COLOR1=B.COLOR2;

-- CROSS JOIN
CREATE TABLE EMPLOYEES( 
	EID INT,
    FNAME VARCHAR(100),
    LNAME VARCHAR(100),
    DID int
);

INSERT INTO EMPLOYEES VALUES(1,"JOHN","DOE",101),(2,"JANE","SMITH",102),(3,"ALICE","JHONSON",103),(4,"BOB","BROWN",104);

CREATE TABLE DEPARTMENTS(
	DID INT,
    DNAME VARCHAR(100)
    );
    
INSERT INTO DEPARTMENTS VALUES(101,"SALES"),(102,"MARKETING"),(103,"HR");

SELECT * FROM EMPLOYEES CROSS JOIN DEPARTMENTS;
