-- CREATE DATABASE CODEGNAN1;
-- USE CODEGNAN1;
-- CREATE TABLE USER1 (ID INT,NAME VARCHAR(50),MOBILE BIGINT,COURSE VARCHAR(10));
-- DESCRIBE USER1;
-- create table products (id int,name varchar(100),price int);
-- describe user2;
-- DESCRIBE PRODUCTS;
-- CREATE TABLE VARUN1 (ID INT,NAME VARCHAR(10),SECTION VARCHAR(10)); 
-- DESCRIBE VARUN1;
-- desc user1;
-- ALTER TABLE USER1 ADD EAMIL VARCHAR(100);
-- DESC USER1;
-- ALTER TABLE USER1 ADD (X1 INT,X2 INT);
-- DESC USER1;
-- DESC PRODUCTS;
-- ALTER TABLE PRODUCTS ADD (DIS_PRICE INT,MFG_DATE DATE,EXP_DATE DATE);
-- DESC PRODUCTS;
-- DESC VARUN1;
-- ALTER TABLE VARUN1 ADD(EMAIL VARCHAR(10));
-- ALTER TABLE USER1 DROP COLUMN X1;
-- DESC USER1;
-- ALTER TABLE USER1 DROP COLUMN X2;
-- DESC USER1;
-- DESC VARUN1;
-- ALTER TABLE VARUN1 DROP COLUMN EMAIL;
-- DESC VARUN1;
-- DESC USER1;
-- ALTER TABLE USER1 MODIFY COLUMN MOBILE INT;
-- DESC USER1;
-- DESC VARUN1;
-- ALTER TABLE VARUN1 MODIFY COLUMN ID BIGINT;
-- DROP TABLE USER2;
-- DESC USER2;
-- DROP TABLE PRODUCTS;
-- DESC PRODUCTS;
-- SELECT * FROM USER1;
-- SELECT NAME,ID FROM USER1;
-- SELECT * FROM VARUN1;
-- SELECT ID,SECTION FROM VARUN1;
-- INSERT INTO VARUN1 (ID,NAME,SECTION) VALUES(1,"VARUN","A");
-- DESC VARUN1;
-- SELECT * FROM VARUN1;




 

