CREATE DATABASE SUBQUERIES;
USE SUBQUERIES;

CREATE TABLE EMPLOYEES( 
	EID INT,
    FNAME VARCHAR(100),
    LNAME VARCHAR(100),
    DID int
);

INSERT INTO EMPLOYEES VALUES(1,"JOHN","DOE",101),(2,"JANE","SMITH",102),(3,"ALICE","JHONSON",103),(4,"BOB","BROWN",104);

SET SQL_SAFE_UPDATES=0;
UPDATE EMPLOYEES SET DID=101 WHERE DID=103;

CREATE TABLE DEPARTMENTS(
	DID INT,
    DNAME VARCHAR(100)
    );
    
INSERT INTO DEPARTMENTS VALUES(101,"SALES"),(102,"MARKETING"),(103,"HR");

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

-- WE NEED TO Retrieve the first and last names of all employees who work in the 'Sales' department USING SUBQUEREIES.

SELECT FNAME,LNAME FROM EMPLOYEES WHERE DID=(SELECT DID FROM DEPARTMENTS WHERE DNAME="SALES");

-- THIS IS USING JOINS CONCEPT 

SELECT FNAME,LNAME FROM EMPLOYEES LEFT JOIN DEPARTMENTS ON EMPLOYEES.DID=DEPARTMENTS.DID WHERE DEPARTMENTS.DNAME="SALES";

-- INDEXING 

CREATE INDEX IDX_LNAME ON EMPLOYEES (LNAME);

SELECT * FROM Employees WHERE LNAME = 'Doe';
SELECT * FROM Employees WHERE LName = 'Doe';
DROP INDEX IDX_LNAME ON EMPLOYEES;


    