use constraints;

CREATE TABLE USERS (
	USER_ID INT PRIMARY KEY NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    AGE INT DEFAULT 0
    );
    
CREATE TABLE ORDERS (
	ORDER_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    PRICE INT DEFAULT 0,
    UID INT NOT NULL,
    FOREIGN KEY (UID) REFERENCES USERS(USER_ID)
    );
    
DESC USERS;

DESC ORDERS;

INSERT INTO USERS VALUES(1,"VARUN",30);
SELECT * FROM USERS;

INSERT INTO ORDERS VALUES(101,"SOAP",100,1001);
INSERT INTO ORDERS VALUES(101,"SOAP",100,1);

SELECT * FROM ORDERS;

INSERT INTO USERS VALUES(2,"SHEERISH",32);
INSERT INTO ORDERS VALUES(102,"COMB",40,1);
INSERT INTO ORDERS VALUES(103,"BRUSH",20,2);

