CREATE DATABASE STRING_OPERATIONS;
USE STRING_OPERATIONS;

CREATE TABLE STUDENT(
	FNAME VARCHAR(100),
    LNAME VARCHAR(100),
    CITY VARCHAR(100)
    );

INSERT INTO STUDENT VALUES("PATHI","VARUN","SURYAPET"),("VANAPARTHY","SATHWIK","SURYAPET"),("NAMALA","SAI SATHVIK","WARANGAL");

SELECT* FROM STUDENT;

-- CONCAT
SELECT *,CONCAT(FNAME,"-",LNAME) AS FULLNAME FROM STUDENT;
SELECT *,CONCAT(SUBSTRING(FNAME,1,1),".",LNAME) AS FULLNAME FROM STUDENT;
SELECT *,CONCAT(LEFT(FNAME,1),".",LNAME) AS FULLNAME FROM STUDENT;

-- CONCAT_WS
SELECT *,CONCAT_WS("/",LNAME,CITY) AS DETAILS FROM STUDENT;
-- LOWER 
SELECT *,CONCAT(LOWER(FNAME)," ",LOWER(LNAME)," ",LOWER(CITY)) AS LOWERCASE FROM STUDENT;

SET SQL_SAFE_UPDATES=0;
UPDATE STUDENT SET LNAME="varun" WHERE LNAME="VARUN";

 -- UPPER 
 SELECT LNAME,UPPER(LNAME) AS UPPER FROM STUDENT;

-- LENGTH,CHAR_LENGTH
SELECT*,LENGTH(FNAME) AS COUNT ,CHAR_LENGTH(LNAME) AS COUNT2,LENGTH(CITY) AS COUNT3 FROM STUDENT;

-- USING CONCAT AND LENGTH FUNCTIONS
SELECT CONCAT(FNAME,"-",LENGTH(FNAME)) AS FNAME,
		CONCAT(LNAME,"-",LENGTH(LNAME)) AS LNAME,
        CONCAT(CITY,"-",LENGTH(CITY)) AS CITY
FROM STUDENT;

-- SUBSTRING
SELECT *,SUBSTRING(FNAME,2,4) AS SUBSTRING_FUNCTION FROM STUDENT;

-- USING CONCAT,CONCAT_WS AND SUBSTRINGS
SELECT CONCAT_WS(" - ",FNAME,SUBSTRING(FNAME,2,4)) AS FNAME,
		CONCAT(LNAME," - ",SUBSTRING(LNAME,1,3)) AS LNAME,
        CONCAT_WS(" - ",CITY,SUBSTRING(CITY,1,3)) AS CITY
FROM STUDENT;

-- REVERSE
SELECT *,REVERSE(FNAME) AS REVERSESTRING,
		REVERSE(LNAME) AS REVERSESTRING,
        REVERSE(CITY) AS REVERSESTRING
FROM STUDENT;

-- USING CONCAT AND REVERSE
SELECT CONCAT(FNAME," - ",REVERSE(FNAME)) AS FNAME,
		CONCAT(LNAME," - ",REVERSE(LNAME)) AS LNAME,
        CONCAT(CITY," - ",REVERSE(CITY)) AS CITY
FROM STUDENT;

-- REPLACE
SELECT *,REPLACE(LNAME,"SATH","X") AS REPLACSTRING FROM STUDENT;

-- LIKE 
SELECT * FROM STUDENT WHERE CITY LIKE "%PET";
SELECT * FROM STUDENT WHERE LNAME LIKE "%SATH_IK";


