CREATE DATABASE FRUITS;
USE FRUITS;
CREATE TABLE FRUIT_SHOP(
	ID INT KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    QUANTITY BIGINT NOT NULL,
    COUNTER_NUMBER INT NOT NULL
    );
CREATE TABLE APPLE_STORE(QUANTITY BIGINT,COUNTER_NUMBER INT);
CREATE TABLE MANGO_STORE(QUANTITY BIGINT,COUNTER_NUMBER INT);
INSERT INTO FRUIT_SHOP(ID,NAME,QUANTITY,COUNTER_NUMBER) VALUES(1,"APPLES",10,101),(2,"MANGOES",15,102);
SELECT * FROM FRUIT_SHOP;
INSERT INTO FRUIT_SHOP(NAME,QUANTITY,COUNTER_NUMBER) VALUES("WATERMELONS",2,103);
INSERT INTO APPLE_STORE(QUANTITY,COUNTER_NUMBER) SELECT QUANTITY,COUNTER_NUMBER FROM FRUIT_SHOP WHERE ID=1;
SELECT * FROM APPLE_STORE;
INSERT INTO FRUIT_SHOP(NAME,QUANTITY,COUNTER_NUMBER) VALUES("APPLES",15,104),("APPLES",20,105),("MANGOES",20,106),("MANGOES",23,107);
INSERT INTO APPLE_STORE(QUANTITY,COUNTER_NUMBER) SELECT QUANTITY,COUNTER_NUMBER FROM FRUIT_SHOP WHERE NAME="APPLES";
TRUNCATE APPLE_STORE;
INSERT INTO MANGO_STORE(QUANTITY,COUNTER_NUMBER) SELECT QUANTITY,COUNTER_NUMBER FROM FRUIT_SHOP WHERE NAME="MANGOES";
SELECT * FROM MANGO_STORE;
