create database operators;
use operators;

CREATE TABLE CUSTOMERS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    AGE INT,
    STATUS VARCHAR(10)
    );
    
INSERT INTO CUSTOMERS(NAME,AGE,STATUS) VALUES("SAI",28,"MAJOR"),("VARUN",22,"MAJOR"),("VIKRAM",18,"MINOR");

SELECT * FROM CUSTOMERS;

INSERT INTO CUSTOMERS(NAME,AGE) VALUES("VISHNU",18),("VIVEK",16),("CHARY",8);

-- ARTHEMATIC OPERATORS

SELECT NAME,ID,AGE,(AGE+ID) AS ADD_OPERATOR FROM CUSTOMERS;
SELECT NAME,AGE,ID,(AGE-ID) AS SUB_OPERATOR FROM CUSTOMERS;
SELECT NAME,AGE,(AGE*10) AS MULTIPLY_OPERATOR FROM CUSTOMERS;
SELECT NAME,ID,AGE,(AGE/ID) AS DIV_OPERATOR FROM CUSTOMERS;
SELECT NAME,ID,AGE,(AGE%ID) AS MODULO_OPERATOR FROM CUSTOMERS;

-- RELATIONAL OPERATORS

SELECT NAME,ID,AGE FROM CUSTOMERS WHERE AGE=18;
SELECT NAME,ID,AGE FROM CUSTOMERS WHERE AGE>18;
SELECT NAME,ID,AGE FROM CUSTOMERS WHERE AGE<18;
SELECT NAME,ID,AGE FROM CUSTOMERS WHERE AGE>=18;
SELECT NAME,ID,AGE FROM CUSTOMERS WHERE AGE<=18;
SELECT NAME,ID,AGE FROM CUSTOMERS WHERE AGE!=18;

-- LOGICAL OPERATORS

SELECT NAME,ID,AGE FROM CUSTOMERS WHERE STATUS="MAJOR" AND AGE!=0;
SELECT NAME,ID,AGE FROM CUSTOMERS WHERE STATUS="MAJOR" OR STATUS="MINOR";
SELECT NAME,ID,AGE FROM CUSTOMERS WHERE STATUS IS NOT NULL;

-- NULL OPERATORS
SELECT NAME,ID,STATUS,AGE FROM CUSTOMERS WHERE STATUS IS NULL;
SELECT NAME,ID,STATUS,AGE FROM CUSTOMERS WHERE STATUS IS NOT NULL;

-- SPECIAL OPERATORS 
SELECT ID,NAME,AGE,STATUS FROM CUSTOMERS WHERE AGE BETWEEN 18 AND 20;
SELECT ID, NAME, AGE, STATUS FROM CUSTOMERS WHERE STATUS IN ('MINOR');
SELECT ID,NAME,AGE,STATUS,
	CASE 
		WHEN AGE>=18 THEN "SINEOR"
        WHEN AGE<18 THEN "JUNIOR"
        END AS AGE_GROUP
        FROM CUSTOMERS;

 